# install packages
brew 'autoconf'
brew 'coreutils'
brew 'git'
brew 'curl'
brew 'wget'
brew 'zsh' # in order to update it if outdated

# install casks
cask '1password'
cask 'bitwarden'
cask 'discord'
cask 'docker'
cask 'google-chrome'
cask 'firefox'
cask 'iterm2'
cask 'loom'
cask 'microsoft-edge'
cask 'mongodb-compass'
cask 'mysqlworkbench'
cask 'notion'
cask 'opera'
cask 'postman'
cask 'slack'
cask 'spotify'
cask 'visual-studio-code'
cask 'whatsapp'
cask 'zoom'
